api_platform:
  title: 'E-Commerce API'
  description: 'An E-Commerce API by symfony :).'
  version: 1.0.0
  mapping:
    paths: ['%kernel.project_dir%/src/Entity']
  patch_formats:
    json: ['application/merge-patch+json']
  swagger:
    versions: [3]
